package com.devices.service;

import com.devices.api.dto.DeviceCreateRequest;
import com.devices.api.dto.DeviceResponse;
import com.devices.api.mapper.DeviceMapper;
import com.devices.model.DeviceState;
import com.devices.persistence.Device;
import com.devices.persistence.DeviceRepository;

import java.time.OffsetDateTime;
import java.util.Objects;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class DeviceService {

    private final DeviceRepository deviceRepository;
    private final DeviceMapper deviceMapper;

    public DeviceService(DeviceRepository deviceRepository, DeviceMapper deviceMapper) {
        this.deviceRepository = deviceRepository;
        this.deviceMapper = deviceMapper;
    }

    @Transactional
    public DeviceResponse create(DeviceCreateRequest request) {
        Objects.requireNonNull(request, "request must not be null");
        Device device = deviceMapper.toEntity(request);
        device.setState(DeviceState.AVAILABLE);
        device.setCreatedAt(OffsetDateTime.now());
        // id will be generated by application (UUID) or DB depending on entity configuration
        Device saved = deviceRepository.save(device);
        return deviceMapper.toResponse(saved);
    }
}
